In [1]:
import numpy as np

In [2]:
a = np.array([2, 5, 10])
a.dtype

dtype('int64')

In [3]:
A=np.array([(3,4,5),(12,6,1)])
Z=np.zeros((2,4))

Z

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
A

array([[ 3,  4,  5],
       [12,  6,  1]])

In [5]:
S=np.arange(10,30,5)
S

array([10, 15, 20, 25])

In [6]:
S = np.arange(0, 2, 0.4)
S

array([0. , 0.4, 0.8, 1.2, 1.6])

In [9]:
S1=np.linspace(0,2,9)
S1

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [10]:
import random

In [11]:
random.choice([1,2,3,4, 5])

5

In [12]:
random.choice('hello')

'l'

In [13]:
random.randrange(0,25)

10

In [14]:
random.randrange(0,25,3)

12

In [15]:
random.uniform(0, 5)

4.912037953798087

In [18]:
a=[1, 2, 3, 4, 5]
random.shuffle(a)
a

[1, 5, 2, 4, 3]

In [19]:
# sets a seed value for this notebook so that the values are reproducible
random.seed(10)

In [20]:
a = np.arange(15).reshape(3, 5)

In [21]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [22]:
c = np.arange(24).reshape(2,3,4)

In [23]:
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [24]:
c.shape

(2, 3, 4)

In [25]:
c[1, :, :]

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [26]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [27]:
a**2

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196]])

In [29]:
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [30]:
np.sin(c)

array([[[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
        [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
        [ 0.98935825,  0.41211849, -0.54402111, -0.99999021]],

       [[-0.53657292,  0.42016704,  0.99060736,  0.65028784],
        [-0.28790332, -0.96139749, -0.75098725,  0.14987721],
        [ 0.91294525,  0.83665564, -0.00885131, -0.8462204 ]]])

In [31]:
a**2

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196]])

In [32]:
a<10

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [False, False, False, False, False]])

In [33]:
A = np.array( [[1,1],[0,1]] )
B = np.array( [[2,0],[3,4]] )

In [34]:
A*B

array([[2, 0],
       [0, 4]])

In [35]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [37]:
B.sum(axis=0)

array([5, 4])

In [38]:
B.sum(axis=1)

array([2, 7])

In [39]:
a = np.arange(10)**3

In [40]:
a[2:5]

array([ 8, 27, 64])

In [41]:
# indices 0 to 8 in steps of 2
a[0:8:2]

array([  0,   8,  64, 216])

In [43]:
#last row
a.reshape(2, 5)[-1, :]

array([125, 216, 343, 512, 729])

In [45]:
b = np.array([[ 0, 1, 2, 3],
[10, 11, 12, 13],
[20, 21, 22, 23],
[30, 31, 32, 33],
[40, 41, 42, 43]])

In [49]:
B = b.reshape((2, 10))

In [50]:
B

array([[ 0,  1,  2,  3, 10, 11, 12, 13, 20, 21],
       [22, 23, 30, 31, 32, 33, 40, 41, 42, 43]])

In [51]:
b.ravel()

array([ 0,  1,  2,  3, 10, 11, 12, 13, 20, 21, 22, 23, 30, 31, 32, 33, 40,
       41, 42, 43])

In [55]:
A1=np.array([(3,4,5),(12,6,1)])

A2=np.array([(1,2,6),(-4,3,8)])

In [56]:
np.hstack((A1, A2))

array([[ 3,  4,  5,  1,  2,  6],
       [12,  6,  1, -4,  3,  8]])

In [57]:
np.vstack((A1, A2))

array([[ 3,  4,  5],
       [12,  6,  1],
       [ 1,  2,  6],
       [-4,  3,  8]])

In [58]:
a = np.array([4.,2.])
b = np.array([3.,8.])

In [59]:
np.column_stack((a,b))

array([[4., 3.],
       [2., 8.]])

In [60]:
np.hstack((a,b))

array([4., 2., 3., 8.])

In [62]:
a = np.arange(12)**2 # the first 12 square numbers
i = np.array( [ 1,1,3,8,5 ] ) # an array of indices
a[i] # the elements of a at the positions i

array([ 1,  1,  9, 64, 25])

In [63]:
j = np.array( [ [ 3, 4], [ 9, 7 ] ] ) # a bidimensional array of indices
a[j] # the same shape as j

array([[ 9, 16],
       [81, 49]])

In [64]:
a=np.array([(3,2,9),(1,6,7)])
s1=0
for row in a:
    for col in row:
        s1+=col
print(s1)

28


In [65]:
a=np.array([(3,2,9),(1,6,7)])
s=0
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        s+=a[i,j]
print(s)

28
